x-logging: &default-logging
  driver: json-file
  options:
    max-file: '3'
    max-size: '10m'

services:
  app:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_HOST: database
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:?}
    image: ruwordnetview:prod
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - shared_web:/var/www/html/web:rw

  database:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
    image: postgres:15.17
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  proxy:
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL:?}
      - CERTBOT_AUTHENTICATOR=dns-cloudflare
      - STAGING=0
    # Has to be built beforehand.
    # See https://github.com/Zebradil/RuWordNetView/blob/master/Makefile
    image: ruwordnetview:nginx
    logging: *default-logging
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      # Volume for nginx cache
      - nginx_cache:/var/cache/nginx:rw
      - nginx_secrets:/etc/letsencrypt
      - shared_web:/var/www/html/web:ro

volumes:
  db_data:
  nginx_cache:
  nginx_secrets:
  shared_web:
