proxy_cache_path /var/cache/nginx/proxy levels=1:2 keys_zone=proxy_cache:100m max_size=10g inactive=60d use_temp_path=off;
proxy_cache_key "$scheme$request_method$host$request_uri";

server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    server_name ruwordnet.ru;

    # Load the certificate files.
    ssl_certificate /etc/letsencrypt/live/ruwordnet.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ruwordnet.ru/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/ruwordnet.ru/chain.pem;

    location / {
        add_header X-Cache-Status $upstream_cache_status;

        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache proxy_cache;
        proxy_cache_lock on;
        proxy_cache_use_stale error timeout updating invalid_header http_500 http_503;
        proxy_cache_valid 200 302 60d;
    }
}
